class_header
NAME
class_header
SYNOPSIS
#include <object_internal.h>
Data Fields
unsigned long magic
size_t size
size_t(* get_size )(const void *_self)
Get size of object in bytes.
size_t(* get_len )(const void *_self)
Get number of items in container object.
const void *(* object_init )(const void *_self, size_t argc, va_list args)
Create and initialize an object.
void(* object_deinit )(const void *_self)
void(* print )(const void *_self)
const char *(* str )(const void *_self)
void *(* to_String )(const void *_self)
const void *(* append )(const void *_self, const void *_other)
bool(* equals )(const void *_self, const void *_other)
const void *(* iter )(const void *_object)
const void *(* copy )(const void *_self)
void(* insert )(const void *_self, const void *_key, const void *item)
const void *(* get_item )(const void *_self, const void *_key)
void(* del_item )(const void *_self, const void *key)
uint64_t(* hash )(const void *_self)
const void *(* next )(const void *_self)
const char * object_name
struct OOCTraitMath math
Detailed Description
All ooc classes have a class_header.
The header provides function pointers to implementations of all supported methods for a given class.
Each object (instantiation of a class) has a pointer to the per-class class_header.
A minimum class must at least provide implementations for magic, size, object_init, object_deinit and object_name
Definition at line 22 of file object_internal.h.
Field Documentation
const void*(* class_header::append) (const void *_self, const void *_other)
Implement to enable appending items to an class. If an class supports appending, it should probably support either get, or iteration.
Parameters:
_self ooc container object
_other ooc object supported by container
Definition at line 99 of file object_internal.h.
Referenced by append().
const void*(* class_header::copy) (const void *_self)
Copy an ooc object.
Implement functionality to copy an object. The expectation is that it is deep copy. Perhaps there should be a convention for shallow copies
Parameters:
_self
Returns:
copy of _self
Definition at line 132 of file object_internal.h.
Referenced by copy().
void(* class_header::del_item) (const void *_self, const void *key)
Implement to enabled indexed deletion from a collection.
Parameters:
_self ooc object
key key to delete
Definition at line 170 of file object_internal.h.
bool(* class_header::equals) (const void *_self, const void *_other)
Implement to allow objects to be compared with a custom function.
Parameters:
_self
_other
Returns:
true if objects are equal. If not implemented, equals will compare pointers
Definition at line 110 of file object_internal.h.
const void*(* class_header::get_item) (const void *_self, const void *_key)
Implement to enable indexed access. value = get(collection, key) value = collection[key]
Typically, key must be in collection, or this function should exit early with an error.
Parameters:
_self ooc object
_key ooc object key
Returns:
Definition at line 160 of file object_internal.h.
size_t(* class_header::get_len) (const void *_self)
Get number of items in container object.
Parameters:
_self ooc object
Returns:
number of items in container
Definition at line 38 of file object_internal.h.
Referenced by len().
size_t(* class_header::get_size) (const void *_self)
Get size of object in bytes.
Parameters:
_self ooc object
Returns:
size in bytes
Definition at line 31 of file object_internal.h.
Referenced by size().
uint64_t(* class_header::hash) (const void *_self)
Implement to enable storing in a hash table.
Note: as of now, HashTables will also use equals() to confirm keys are unique. If hash is not implemented, as of now, the HashTable does not support it. This may change in the future.
Parameters:
_self ooc object
Returns:
64 bit user defined hash
Definition at line 187 of file object_internal.h.
Referenced by del_item_HashMap(), get_HashMap(), insert_HashMap(), and internal_insert_HashMap().
void(* class_header::insert) (const void *_self, const void *_key, const void *item)
Implement to enable indexed assignment. insert(collection, key, value) is equivalent to collection[key] = value
Parameters:
_self ooc object
_key ooc object key to index into collection
item value to store at given index
Definition at line 143 of file object_internal.h.
const void*(* class_header::iter) (const void *_object)
Return an iterator to support iteration.
Parameters:
_object ooc object
Returns:
ooc iterator
Definition at line 120 of file object_internal.h.
unsigned long class_header::magic
Definition at line 23 of file object_internal.h.
Referenced by get_obj_type().
struct OOCTraitMath class_header::math
Traits
Definition at line 207 of file object_internal.h.
Referenced by List_get_item(), and obj_add().
const void*(* class_header::next) (const void *_self)
Implement to support iteration. You must implement iter() and next() to support iteration.
Parameters:
_self iterable returned from iter()
Returns:
next item in iteration.
Definition at line 197 of file object_internal.h.
void(* class_header::object_deinit) (const void *_self)
De-initialize and free resources used by _self.
Parameters:
_self ooc object
Definition at line 57 of file object_internal.h.
Referenced by del().
const void*(* class_header::object_init) (const void *_self, size_t argc, va_list args)
Create and initialize an object. It also correct to calll this the object constructor.
Parameters:
_self ooc class like String or HashMap.
argc number of arguments
args arguments to initialize object. Varies based on class type
Returns:
Definition at line 50 of file object_internal.h.
Referenced by _new().
const char* class_header::object_name
Object name as C string
Definition at line 202 of file object_internal.h.
Referenced by clsname().
void(* class_header::print) (const void *_self)
Print and object to stdout
Parameters:
_self ooc object
Definition at line 63 of file object_internal.h.
Referenced by print().
size_t class_header::size
Definition at line 24 of file object_internal.h.
Referenced by _new(), and List_get_size().
const char*(* class_header::str) (const void *_self)
Return the c string (char*) representation of an object
May be used by to_String to make an ooc String representation. Usually it's not necessary to implement to_String separately.
Parameters:
_self ooc object
Returns:
c string representation
Definition at line 76 of file object_internal.h.
Referenced by str().
void*(* class_header::to_String) (const void *_self)
Return String representation of object.
May allocate a new String object, and may or may not return a different String object each time.
Usually it is sufficient to implement str.
Parameters:
_self ooc objet
Returns:
ooc String object
Definition at line 89 of file object_internal.h.
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.