collection
NAME
collection
SYNOPSIS
Functions
const void * append (const void *_object, const void *_other)
void * set_item (const void *_self, const void *_key, const void *item)
const void * get_item (const void *_self, const void *_key)
struct class_header * get_class_header_msg (const void *_self, const char *message)
const struct class_header * get_obj_type (const void *_self, const void *class, const char *message)
const void * iter (const void *_object)
uint64_t hash (const void *_self)
const void * next (const void *_self)
void del_item (const void *_self, const void *key)
Detailed Description
Function Documentation
const void* append (const void * _object, const void * _other)
Definition at line 165 of file object.c.
References class_header::append, clsname(), and get_class_header_msg().
Referenced by List_to_str().
void del_item (const void * _self, const void * key)
Definition at line 244 of file object.c.
References get_class_header(), and get_class_header_msg().
struct class_header* get_class_header_msg (const void * _self, const char * message) [inline]
Definition at line 182 of file object.c.
References MAGIC.
Referenced by append(), clsname(), copy(), del(), del_item(), del_item_HashMap(), equals(), get_HashMap(), get_item(), hash(), insert_HashMap(), iter(), len(), List_get_item(), next(), obj_add(), obj_to_int(), print(), set_item(), size(), str(), and type().
const void* get_item (const void * _self, const void * _key)
Definition at line 257 of file object.c.
References clsname(), get_class_header(), and get_class_header_msg().
const struct class_header* get_obj_type (const void * _self, const void * class, const char * message) [inline]
Definition at line 201 of file object.c.
References MAGIC, and class_header::magic.
uint64_t hash (const void * _self)
Definition at line 223 of file object.c.
References get_class_header(), and get_class_header_msg().
Referenced by FNV32().
const void* iter (const void * _object)
Definition at line 269 of file object.c.
References clsname(), get_class_header(), and get_class_header_msg().
Referenced by main().
const void* next (const void * _self)
Definition at line 282 of file object.c.
References get_class_header(), and get_class_header_msg().
Referenced by main().
void* set_item (const void * _self, const void * _key, const void * item)
Definition at line 232 of file object.c.
References get_class_header(), and get_class_header_msg().
Referenced by main().
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.