.TH "common" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const void * \fBnew\fP (const void *class,\&.\&.\&.)"
.br
.RI "Create a new ooc object\&. "
.ti -1c
.RI "const void * \fBtype\fP (const void *self)"
.br
.RI "get ooc class object "
.ti -1c
.RI "void \fBdel\fP (const void *_object)"
.br
.ti -1c
.RI "size_t \fBsize\fP (const void *_object)"
.br
.ti -1c
.RI "const char * \fBclsname\fP (const void *_self)"
.br
.ti -1c
.RI "void \fBprint\fP (const void *_object)"
.br
.ti -1c
.RI "size_t \fBlen\fP (const void *_object)"
.br
.ti -1c
.RI "const void * \fBcopy\fP (const void *_object)"
.br
.ti -1c
.RI "bool \fBequals\fP (const void *_object, const void *_other)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "const char* clsname (const void * _self)"

.PP
Definition at line 105 of file object\&.c\&.
.PP
References get_obj(), and class_header::object_name\&.
.PP
Referenced by main(), and String_equal()\&.
.SS "const void* copy (const void * _object)"

.PP
Definition at line 121 of file object\&.c\&.
.PP
References class_header::copy, and get_obj()\&.
.PP
Referenced by main()\&.
.SS "void del (const void * _object)"

.PP
Definition at line 34 of file object\&.c\&.
.PP
References get_obj(), and class_header::object_deinit\&.
.SS "bool equals (const void * _object, const void * _other)"

.PP
Definition at line 135 of file object\&.c\&.
.PP
References get_obj()\&.
.PP
Referenced by get_HashMap(), and internal_insert_HashMap()\&.
.SS "size_t len (const void * _object)"

.PP
Definition at line 91 of file object\&.c\&.
.PP
References class_header::get_len, and get_obj()\&.
.PP
Referenced by __construct__String(), FNV32(), and String_append()\&.
.SS "const void* new (const void *const _class,  \&.\&.\&.)"

.PP
Create a new ooc object\&. This function allocates memory and returns a void* to a newly allocated ooc object, or NULL on failure\&.
.PP
_class should be a pointer to an ooc class object, such as \fBString\fP or \fBHashMap\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclass\fP ooc class object 
.RE
.PP
\fBReturns:\fP
.RS 4
new object or type class, or NULL
.RE
.PP
\fBParameters:\fP
.RS 4
\fI_class\fP 
.br
\fI\&.\&.\&.\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 15 of file object\&.c\&.
.PP
References MAGIC\&.
.SS "void print (const void * _object)"

.PP
Definition at line 59 of file object\&.c\&.
.PP
References get_obj(), and class_header::print\&.
.PP
Referenced by main()\&.
.SS "size_t size (const void * _object)"

.PP
Definition at line 72 of file object\&.c\&.
.PP
References get_obj(), and class_header::get_size\&.
.PP
Referenced by __construct__Person(), __construct__String(), and String_append()\&.
.SS "const void* type (const void * self)"

.PP
get ooc class object 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP ooc object 
.RE
.PP
\fBReturns:\fP
.RS 4
ooc class of a given ooc object 
.RE
.PP

.PP
Definition at line 83 of file object\&.c\&.
.PP
References get_obj()\&.
.PP
Referenced by String_append(), and String_equal()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
