common
NAME
common
SYNOPSIS
Functions
const void * _new (size_t argc,...)
Create a new ooc object.
const void * type (const void *self)
get ooc class object
void del (const void *object)
delete an ooc object
size_t size (const void *_object)
get size in bytes
const char * clsname (const void *_self)
void print (const void *_object)
size_t len (const void *_object)
const void * copy (const void *_object)
bool equals (const void *_object, const void *_other)
Detailed Description
Function Documentation
const void* _new (size_t argc, ...)
Create a new ooc object. This function allocates memory and returns a void* to a newly allocated ooc object, or NULL on failure.
_class should be a pointer to an ooc class object, such as String or HashMap.
Parameters:
class ooc class object
argc number of arguments provided
Returns:
new object or type class, or NULL
Parameters:
class OOC class to instantiate
... arguments to initialize class
Returns:
Definition at line 17 of file object.c.
References ObjectHeader::class, MAGIC, class_header::object_init, and class_header::size.
const char* clsname (const void * _self)
Definition at line 120 of file object.c.
References get_class_header_msg(), and class_header::object_name.
Referenced by append(), get_item(), iter(), len(), List_get_item(), obj_add(), obj_to_int(), and String_equal().
const void* copy (const void * _object)
Definition at line 136 of file object.c.
References class_header::copy, and get_class_header_msg().
Referenced by main().
void del (const void * object)
delete an ooc object
Parameters:
object
Definition at line 44 of file object.c.
References get_class_header_msg(), and class_header::object_deinit.
bool equals (const void * _object, const void * _other)
Definition at line 150 of file object.c.
References get_class_header_msg().
Referenced by get_HashMap(), and internal_insert_HashMap().
size_t len (const void * _object)
Definition at line 106 of file object.c.
References clsname(), get_class_header_msg(), and class_header::get_len.
Referenced by __construct__String(), FNV32(), and String_append().
void print (const void * _object)
Definition at line 74 of file object.c.
References get_class_header_msg(), and class_header::print.
Referenced by main().
size_t size (const void * _object)
get size in bytes Get the full size in bytes of an ooc object. This is implementation defined, and may not include the size of items contained in a collection for example
Parameters:
_object
Returns:
size in bytes of object
Definition at line 87 of file object.c.
References get_class_header_msg(), and class_header::get_size.
Referenced by __construct__Person(), __construct__String(), and String_append().
const void* type (const void * self)
get ooc class object
Parameters:
self ooc object
Returns:
ooc class of a given ooc object
Definition at line 98 of file object.c.
References get_class_header_msg().
Referenced by String_append(), and String_equal().
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.