/Users/igutek/Documents/Projects/ooc/src/hashmap.c
NAME
/Users/igutek/Documents/Projects/ooc/src/hashmap.c
SYNOPSIS
#include 'object_internal.h'
#include <ooc/hashmap.h>
Data Structures
struct HashItem
struct HashMap
struct HashMap_iter
struct HashMapClass
struct HashMapClass_iter
Macros
#define ODD 1
#define EVEN 0
#define W 64
#define HASH_TABLE_DEFAULT_LEN 4
#define MAX_A 18446744073709551615L
#define HWM_FRACTION 0.5
Typedefs
typedef struct HashItem HashItem
Functions
const void * __construct__HashMap (const void *self, va_list args)
void print_HashMap (void *_self)
size_t get_size_HashMap (const void *_self)
size_t get_len_HashMap (const void *_self)
const char * str_HashMap (const void *_self)
void insert_HashMap (const void *_self, const void *key, const void *_other)
const void * get_HashMap (const void *_self, const void *key)
const void * copy_HashMap (const void *_self)
const void * next_HashMap (const void *_self)
void internal_resize_HashMap (struct HashMap *self, uint64_t new_m)
void internal_print_table (struct HashMap *self)
struct HashItem * alloc_hash_items (size_t n)
uint64_t random_a ()
uint64_t lg (uint64_t n)
uint64_t random_b (uint64_t m)
uint64_t internal_hash (uint64_t a, uint64_t b, uint64_t M, uint64_t key)
void internal_insert_HashMap (struct HashMap *self, const void *_key, const void *_value)
size_t internal_count_HashMap (struct HashMap *self)
void __destruct__HashMap (const void *_self, va_list args)
void del_item_HashMap (const void *_self, const void *_key)
const void * iter_HashMap (const void *_self)
const void * __construct__HashMap_iter (const void *_self, va_list args)
Variables
bool rng_seeded = false
struct HashMapClass hash_map_class
void * HashMap = &hash_map_class
struct HashMapClass_iter hash_map_class_iter
void * HashMap_iter = &hash_map_class_iter
Macro Definition Documentation
#define EVEN 0
Definition at line 38 of file hashmap.c.
#define HASH_TABLE_DEFAULT_LEN 4
Definition at line 43 of file hashmap.c.
Referenced by __construct__HashMap(), and internal_resize_HashMap().
#define HWM_FRACTION 0.5
Definition at line 45 of file hashmap.c.
Referenced by __construct__HashMap(), and internal_resize_HashMap().
#define MAX_A 18446744073709551615L
Definition at line 44 of file hashmap.c.
Referenced by random_a().
#define ODD 1
Definition at line 37 of file hashmap.c.
#define W 64
Definition at line 42 of file hashmap.c.
Referenced by internal_hash(), and random_b().
Typedef Documentation
typedef struct HashItem HashItem
Definition at line 12 of file hashmap.c.
Function Documentation
const void * __construct__HashMap (const void * self, va_list args)
Definition at line 277 of file hashmap.c.
References alloc_hash_items(), HASH_TABLE_DEFAULT_LEN, HashMap, HWM_FRACTION, lg(), random_a(), random_b(), rng_seeded, and HashMap::size.
const void* __construct__HashMap_iter (const void * _self, va_list args)
Definition at line 500 of file hashmap.c.
References HashMap_iter::class, and HashMap_iter.
void __destruct__HashMap (const void * _self, va_list args)
Definition at line 307 of file hashmap.c.
struct HashItem* alloc_hash_items (size_t n)
Definition at line 73 of file hashmap.c.
Referenced by __construct__HashMap(), and internal_resize_HashMap().
const void * copy_HashMap (const void * _self)
Definition at line 514 of file hashmap.c.
void del_item_HashMap (const void * _self, const void * _key)
Definition at line 378 of file hashmap.c.
References get_obj(), class_header::hash, internal_hash(), HashItem::internal_key, internal_print_table(), internal_resize_HashMap(), HashItem::next, HashItem::present, and HashItem::value.
const void * get_HashMap (const void * _self, const void * key)
Definition at line 343 of file hashmap.c.
References equals(), get_class_header(), get_obj(), class_header::hash, internal_hash(), HashItem::internal_key, HashItem::key, HashItem::next, str(), and HashItem::value.
size_t get_len_HashMap (const void * _self)
Definition at line 256 of file hashmap.c.
References internal_count_HashMap(), and internal_print_table().
size_t get_size_HashMap (const void * _self)
Definition at line 272 of file hashmap.c.
References HashMap::size.
void insert_HashMap (const void * _self, const void * key, const void * _other)
Definition at line 324 of file hashmap.c.
References get_class_header(), get_obj(), class_header::hash, internal_insert_HashMap(), and str().
size_t internal_count_HashMap (struct HashMap * self)
Definition at line 175 of file hashmap.c.
References HashItem::next, and HashItem::present.
Referenced by get_len_HashMap().
uint64_t internal_hash (uint64_t a, uint64_t b, uint64_t M, uint64_t key)
Definition at line 102 of file hashmap.c.
References HashItem::key, and W.
Referenced by del_item_HashMap(), get_HashMap(), and internal_insert_HashMap().
void internal_insert_HashMap (struct HashMap * self, const void * _key, const void * _value)
Definition at line 107 of file hashmap.c.
References equals(), get_class_header(), class_header::hash, internal_hash(), HashItem::internal_key, internal_resize_HashMap(), HashItem::key, HashItem::next, HashItem::present, and HashItem::value.
Referenced by insert_HashMap(), and internal_resize_HashMap().
void internal_print_table (struct HashMap * self)
Definition at line 152 of file hashmap.c.
References HashItem::internal_key, HashItem::next, and HashItem::present.
Referenced by del_item_HashMap(), get_len_HashMap(), and internal_resize_HashMap().
void internal_resize_HashMap (struct HashMap * self, uint64_t new_m)
Definition at line 193 of file hashmap.c.
References alloc_hash_items(), HASH_TABLE_DEFAULT_LEN, HWM_FRACTION, internal_insert_HashMap(), internal_print_table(), HashItem::key, lg(), HashItem::next, HashItem::present, random_a(), random_b(), and HashItem::value.
Referenced by del_item_HashMap(), and internal_insert_HashMap().
const void* iter_HashMap (const void * _self)
Definition at line 453 of file hashmap.c.
References HashMap_iter.
uint64_t lg (uint64_t n)
Definition at line 87 of file hashmap.c.
Referenced by __construct__HashMap(), internal_resize_HashMap(), and random_b().
const void * next_HashMap (const void * _self)
Definition at line 464 of file hashmap.c.
References HashItem::next, and HashItem::value.
void print_HashMap (void * _self)
Definition at line 311 of file hashmap.c.
uint64_t random_a ()
Definition at line 80 of file hashmap.c.
References MAX_A.
Referenced by __construct__HashMap(), and internal_resize_HashMap().
uint64_t random_b (uint64_t m)
Definition at line 96 of file hashmap.c.
References lg(), and W.
Referenced by __construct__HashMap(), and internal_resize_HashMap().
const char * str_HashMap (const void * _self)
Definition at line 317 of file hashmap.c.
Variable Documentation
struct HashMapClass hash_map_class
Initial value:
= {
    .class = {.magic = MAGIC,
              .size = sizeof(struct HashMap),
              .object_init = __construct__HashMap,
              .object_deinit = __destruct__HashMap,
              .get_size = get_size_HashMap,
              .get_len = get_len_HashMap,
              .str = str_HashMap,
              .copy = copy_HashMap,
              .insert = insert_HashMap,
              .get = get_HashMap,
              .del_item = del_item_HashMap,
              .iter = iter_HashMap,
              .object_name = "HashMap"
             }
}
Definition at line 520 of file hashmap.c.
struct HashMapClass_iter hash_map_class_iter
Initial value:
= {
    .class = {.magic = MAGIC,
              .object_init = __construct__HashMap_iter,
              .size = sizeof(struct HashMap_iter),
              .next = next_HashMap
             }
}
Definition at line 541 of file hashmap.c.
void* HashMap = &hash_map_class
Definition at line 539 of file hashmap.c.
Referenced by __construct__HashMap(), and main().
void* HashMap_iter = &hash_map_class_iter
Definition at line 549 of file hashmap.c.
Referenced by __construct__HashMap_iter(), and iter_HashMap().
bool rng_seeded = false
Definition at line 55 of file hashmap.c.
Referenced by __construct__HashMap().
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.