.TH "HashItem" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashItem
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBinternal_key\fP"
.br
.ti -1c
.RI "const void * \fBkey\fP"
.br
.ti -1c
.RI "const void * \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBHashItem\fP * \fBnext\fP"
.br
.ti -1c
.RI "bool \fBpresent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file hashmap\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t HashItem::internal_key"

.PP
Definition at line 6 of file hashmap\&.c\&.
.PP
Referenced by del_item_HashMap(), get_HashMap(), internal_insert_HashMap(), and internal_print_table()\&.
.SS "const void* HashItem::key"

.PP
Definition at line 7 of file hashmap\&.c\&.
.PP
Referenced by get_HashMap(), internal_hash(), internal_insert_HashMap(), and internal_resize_HashMap()\&.
.SS "struct \fBHashItem\fP* HashItem::next"

.PP
Definition at line 9 of file hashmap\&.c\&.
.PP
Referenced by del_item_HashMap(), get_HashMap(), internal_count_HashMap(), internal_insert_HashMap(), internal_print_table(), internal_resize_HashMap(), and next_HashMap()\&.
.SS "bool HashItem::present"

.PP
Definition at line 10 of file hashmap\&.c\&.
.PP
Referenced by del_item_HashMap(), internal_count_HashMap(), internal_insert_HashMap(), internal_print_table(), and internal_resize_HashMap()\&.
.SS "const void* HashItem::value"

.PP
Definition at line 8 of file hashmap\&.c\&.
.PP
Referenced by del_item_HashMap(), get_HashMap(), internal_insert_HashMap(), internal_resize_HashMap(), and next_HashMap()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
