.TH "/Users/igutek/Documents/Projects/ooc/include/ooc/hashmap.h" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/include/ooc/hashmap.h
.SH SYNOPSIS
.br
.PP
\fC#include 'object\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBHashMap\fP"
.br
.ti -1c
.RI "void * \fBHashMap_iter\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void* \fBHashMap\fP"

.PP
Definition at line 547 of file hashmap\&.c\&.
.PP
Referenced by __construct__HashMap(), and main()\&.
.SS "void* \fBHashMap_iter\fP"

.PP
Definition at line 557 of file hashmap\&.c\&.
.PP
Referenced by __construct__HashMap_iter(), and iter_HashMap()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
