.TH "Int" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Int
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Int\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP * \fBclass\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "char * \fBstr_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Int\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP* Int::class"

.PP
Definition at line 8 of file Int\&.h\&.
.SS "size_t Int::size"

.PP
Definition at line 9 of file Int\&.h\&.
.PP
Referenced by get_size_Int()\&.
.SS "char* Int::str_value"

.PP
Definition at line 11 of file Int\&.h\&.
.SS "int Int::value"

.PP
Definition at line 10 of file Int\&.h\&.
.PP
Referenced by __construct__Int()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
