.TH "Int" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Int
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP * \fBclass\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "char \fBstr_value\fP [\fBMAX_STR_SIZE\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file int\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP* Int::class"

.PP
Definition at line 8 of file int\&.c\&.
.SS "size_t Int::size"

.PP
Definition at line 9 of file int\&.c\&.
.PP
Referenced by Int_get_size()\&.
.SS "char Int::str_value[\fBMAX_STR_SIZE\fP]"

.PP
Definition at line 11 of file int\&.c\&.
.SS "int Int::value"

.PP
Definition at line 10 of file int\&.c\&.
.PP
Referenced by Int_add(), Int_div(), Int_init(), Int_mul(), Int_sub(), and Int_to_int()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
