.TH "/Users/igutek/Documents/Projects/ooc/include/ooc/int.h" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/include/ooc/int.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBInt\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void* \fBInt\fP"

.PP
Definition at line 47 of file int\&.c\&.
.PP
Referenced by Int_add(), Int_div(), Int_init(), Int_mul(), and Int_sub()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
