.TH "/Users/igutek/Documents/Projects/ooc/include/ooc/Int.h" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/include/ooc/Int.h
.SH SYNOPSIS
.br
.PP
\fC#include 'object\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBInt\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBInt\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void* \fBInt\fP"

.PP
Definition at line 27 of file Int\&.c\&.
.PP
Referenced by __construct__Int()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
