.TH "IntClass" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntClass
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP \fBclass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file int\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP IntClass::class"

.PP
Definition at line 15 of file int\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
