.TH "ListItem" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListItem
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const void * \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBListItem\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file list\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBListItem\fP* ListItem::next"

.PP
Definition at line 18 of file list\&.c\&.
.PP
Referenced by List_append(), List_get_item(), List_to_str(), and ListIterator_next()\&.
.SS "const void* ListItem::value"

.PP
Definition at line 17 of file list\&.c\&.
.PP
Referenced by List_append(), List_get_item(), List_to_str(), and ListIterator_next()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
