.TH "/Users/igutek/Documents/Projects/ooc/include/ooc/list.h" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/include/ooc/list.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBList\fP"
.br
.ti -1c
.RI "void * \fBListIterator\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void* \fBList\fP"

.PP
Definition at line 239 of file list\&.c\&.
.SS "void* \fBListIterator\fP"

.PP
Definition at line 237 of file list\&.c\&.
.PP
Referenced by List_iter(), and ListIterator_init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
