/Users/igutek/Documents/Projects/ooc/src/list.c
NAME
/Users/igutek/Documents/Projects/ooc/src/list.c
SYNOPSIS
#include <stdint.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ooc/string.h>
#include <ooc/math.h>
#include <assert.h>
#include 'ooc/list.h'
#include 'object_internal.h'
Data Structures
struct ListItem
struct List
struct ListClass
struct ListIterator
struct ListIteratorClass
Typedefs
typedef struct ListItem ListItem
Functions
const void * List_append (const void *_self, const void *_other)
const void * List_init (const void *_self, size_t argc, va_list args)
size_t List_get_size (const void *_self)
size_t List_get_len (const void *_self)
const char * List_to_str (const void *_self)
const void * List_get_item (const void *_self, const void *_index)
const void * List_iter (const void *_self)
const void * ListIterator_init (const void *_self, size_t argc, va_list args)
const void * ListIterator_next (const void *_self)
Variables
struct ListClass List_class
struct ListIteratorClass list_iterator_class
void * ListIterator = &list_iterator_class
void * List = &List_class
Typedef Documentation
typedef struct ListItem ListItem
Definition at line 20 of file list.c.
Function Documentation
const void * List_append (const void * _self, const void * _other)
Definition at line 121 of file list.c.
References ListItem::next, and ListItem::value.
Referenced by List_init().
const void* List_get_item (const void * _self, const void * _index)
Definition at line 142 of file list.c.
References clsname(), get_class_header_msg(), class_header::math, ListItem::next, obj_to_int(), OOCTraitMath::to_int, and ListItem::value.
size_t List_get_len (const void * _self)
Definition at line 73 of file list.c.
References List::len.
size_t List_get_size (const void * _self)
Definition at line 67 of file list.c.
References List::class, and class_header::size.
const void* List_init (const void * _self, size_t argc, va_list args)
Definition at line 49 of file list.c.
References List::len, and List_append().
const void* List_iter (const void * _self)
Definition at line 168 of file list.c.
References ListIterator.
const char* List_to_str (const void * _self)
Definition at line 78 of file list.c.
References append(), ListItem::next, str(), to_String(), and ListItem::value.
const void* ListIterator_init (const void * _self, size_t argc, va_list args)
Definition at line 173 of file list.c.
References ListIterator::class, and ListIterator.
const void* ListIterator_next (const void * _self)
Definition at line 192 of file list.c.
References ListIterator::item, ListItem::next, and ListItem::value.
Variable Documentation
void* List = &List_class
Definition at line 239 of file list.c.
struct ListClass List_class
Initial value:
= {
        .class = {.magic = MAGIC,
                .size = sizeof(struct List),
                .object_init = List_init,
                .get_size = List_get_size,
                .get_len = List_get_len,
                .str = List_to_str,
                .append = List_append,
                .iter = List_iter,
                .get_item = List_get_item,
                .object_name = "List"
        }
}
Definition at line 214 of file list.c.
struct ListIteratorClass list_iterator_class
Initial value:
= {
        .class = {.magic = MAGIC,
                .object_init = ListIterator_init,
                .size = sizeof(struct ListIterator),
                .next = ListIterator_next
        }
}
Definition at line 228 of file list.c.
void* ListIterator = &list_iterator_class
Definition at line 237 of file list.c.
Referenced by List_iter(), and ListIterator_init().
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.