.TH "/Users/igutek/Documents/Projects/ooc/src/list.c" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/src/list.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <ooc/string\&.h>\fP
.br
\fC#include <ooc/math\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'ooc/list\&.h'\fP
.br
\fC#include 'object_internal\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBListItem\fP"
.br
.ti -1c
.RI "struct \fBList\fP"
.br
.ti -1c
.RI "struct \fBListClass\fP"
.br
.ti -1c
.RI "struct \fBListIterator\fP"
.br
.ti -1c
.RI "struct \fBListIteratorClass\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBListItem\fP \fBListItem\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const void * \fBList_append\fP (const void *_self, const void *_other)"
.br
.ti -1c
.RI "const void * \fBList_init\fP (const void *_self, size_t argc, va_list args)"
.br
.ti -1c
.RI "size_t \fBList_get_size\fP (const void *_self)"
.br
.ti -1c
.RI "size_t \fBList_get_len\fP (const void *_self)"
.br
.ti -1c
.RI "const char * \fBList_to_str\fP (const void *_self)"
.br
.ti -1c
.RI "const void * \fBList_get_item\fP (const void *_self, const void *_index)"
.br
.ti -1c
.RI "const void * \fBList_iter\fP (const void *_self)"
.br
.ti -1c
.RI "const void * \fBListIterator_init\fP (const void *_self, size_t argc, va_list args)"
.br
.ti -1c
.RI "const void * \fBListIterator_next\fP (const void *_self)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBListClass\fP \fBList_class\fP"
.br
.ti -1c
.RI "struct \fBListIteratorClass\fP \fBlist_iterator_class\fP"
.br
.ti -1c
.RI "void * \fBListIterator\fP = &\fBlist_iterator_class\fP"
.br
.ti -1c
.RI "void * \fBList\fP = &\fBList_class\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBListItem\fP \fBListItem\fP"

.PP
Definition at line 20 of file list\&.c\&.
.SH "Function Documentation"
.PP 
.SS "const void * List_append (const void * _self, const void * _other)"

.PP
Definition at line 121 of file list\&.c\&.
.PP
References ListItem::next, and ListItem::value\&.
.PP
Referenced by List_init()\&.
.SS "const void* List_get_item (const void * _self, const void * _index)"

.PP
Definition at line 142 of file list\&.c\&.
.PP
References clsname(), get_class_header_msg(), class_header::math, ListItem::next, obj_to_int(), OOCTraitMath::to_int, and ListItem::value\&.
.SS "size_t List_get_len (const void * _self)"

.PP
Definition at line 73 of file list\&.c\&.
.PP
References List::len\&.
.SS "size_t List_get_size (const void * _self)"

.PP
Definition at line 67 of file list\&.c\&.
.PP
References List::class, and class_header::size\&.
.SS "const void* List_init (const void * _self, size_t argc, va_list args)"

.PP
Definition at line 49 of file list\&.c\&.
.PP
References List::len, and List_append()\&.
.SS "const void* List_iter (const void * _self)"

.PP
Definition at line 168 of file list\&.c\&.
.PP
References ListIterator\&.
.SS "const char* List_to_str (const void * _self)"

.PP
Definition at line 78 of file list\&.c\&.
.PP
References append(), ListItem::next, str(), to_String(), and ListItem::value\&.
.SS "const void* ListIterator_init (const void * _self, size_t argc, va_list args)"

.PP
Definition at line 173 of file list\&.c\&.
.PP
References ListIterator::class, and ListIterator\&.
.SS "const void* ListIterator_next (const void * _self)"

.PP
Definition at line 192 of file list\&.c\&.
.PP
References ListIterator::item, ListItem::next, and ListItem::value\&.
.SH "Variable Documentation"
.PP 
.SS "void* \fBList\fP = &\fBList_class\fP"

.PP
Definition at line 239 of file list\&.c\&.
.SS "struct \fBListClass\fP List_class"
\fBInitial value:\fP
.PP
.nf
= {
        \&.class = {\&.magic = MAGIC,
                \&.size = sizeof(struct List),
                \&.object_init = List_init,
                \&.get_size = List_get_size,
                \&.get_len = List_get_len,
                \&.str = List_to_str,
                \&.append = List_append,
                \&.iter = List_iter,
                \&.get_item = List_get_item,
                \&.object_name = "List"
        }
}
.fi
.PP
Definition at line 214 of file list\&.c\&.
.SS "struct \fBListIteratorClass\fP list_iterator_class"
\fBInitial value:\fP
.PP
.nf
= {
        \&.class = {\&.magic = MAGIC,
                \&.object_init = ListIterator_init,
                \&.size = sizeof(struct ListIterator),
                \&.next = ListIterator_next
        }

}
.fi
.PP
Definition at line 228 of file list\&.c\&.
.SS "void* \fBListIterator\fP = &\fBlist_iterator_class\fP"

.PP
Definition at line 237 of file list\&.c\&.
.PP
Referenced by List_iter(), and ListIterator_init()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
