.TH "List" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
List
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP * \fBclass\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "bool \fBiterating\fP"
.br
.ti -1c
.RI "struct \fBListItem\fP * \fBhead\fP"
.br
.ti -1c
.RI "struct \fBListItem\fP * \fBtail\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file list\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP* List::class"

.PP
Definition at line 23 of file list\&.c\&.
.PP
Referenced by List_get_size()\&.
.SS "struct \fBListItem\fP* List::head"

.PP
Definition at line 27 of file list\&.c\&.
.SS "bool List::iterating"

.PP
Definition at line 26 of file list\&.c\&.
.SS "size_t List::len"

.PP
Definition at line 25 of file list\&.c\&.
.PP
Referenced by List_get_len(), and List_init()\&.
.SS "size_t List::size"

.PP
Definition at line 24 of file list\&.c\&.
.SS "struct \fBListItem\fP* List::tail"

.PP
Definition at line 28 of file list\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
