.TH "ListIterator" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListIterator
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP * \fBclass\fP"
.br
.ti -1c
.RI "struct \fBList\fP * \fBlist\fP"
.br
.ti -1c
.RI "bool \fBdone\fP"
.br
.ti -1c
.RI "\fBListItem\fP * \fBitem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file list\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP* ListIterator::class"

.PP
Definition at line 37 of file list\&.c\&.
.PP
Referenced by ListIterator_init()\&.
.SS "bool ListIterator::done"

.PP
Definition at line 39 of file list\&.c\&.
.SS "\fBListItem\fP* ListIterator::item"

.PP
Definition at line 40 of file list\&.c\&.
.PP
Referenced by ListIterator_next()\&.
.SS "struct \fBList\fP* ListIterator::list"

.PP
Definition at line 38 of file list\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
