low
NAME
low
SYNOPSIS
Functions
const void * type (const void *_self)
const void * new (const void *_class,...)
void del (const void *_object)
size_t size (const void *_object)
const char * clsname (const void *_self)
Detailed Description
Function Documentation
const char* clsname (const void * _self)
Definition at line 105 of file object.c.
References get_obj(), and class_header::object_name.
Referenced by main(), and String_equal().
void del (const void * _object)
Definition at line 34 of file object.c.
References get_obj(), and class_header::object_deinit.
const void* new (const void *const _class, ...)
Parameters:
_class
...
Returns:
Definition at line 15 of file object.c.
References MAGIC.
size_t size (const void * _object)
Definition at line 72 of file object.c.
References get_obj(), and class_header::get_size.
Referenced by __construct__Person(), __construct__String(), and String_append().
const void* type (const void * _self)
Definition at line 83 of file object.c.
References get_obj().
Referenced by String_append(), and String_equal().
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.