.TH "/Users/igutek/Documents/Projects/ooc/src/main.c" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <ooc/point\&.h>\fP
.br
\fC#include <ooc/person\&.h>\fP
.br
\fC#include <ooc/string\&.h>\fP
.br
\fC#include <ooc/Int\&.h>\fP
.br
\fC#include <ooc/hashmap\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 8 of file main\&.c\&.
.PP
References clsname(), copy(), HashMap, insert(), iter(), next(), Point, print(), and String\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
