/Users/igutek/Documents/Projects/ooc/src/main.c
NAME
/Users/igutek/Documents/Projects/ooc/src/main.c
SYNOPSIS
#include <ooc/point.h>
#include <ooc/person.h>
#include <ooc/string.h>
#include <ooc/Int.h>
#include <ooc/hashmap.h>
#include <assert.h>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 8 of file main.c.
References clsname(), copy(), HashMap, insert(), iter(), next(), Point, print(), and String.
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.