.TH "/Users/igutek/Documents/Projects/ooc/src/math.c" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/src/math.c
.SH SYNOPSIS
.br
.PP
\fC#include <ooc/math\&.h>\fP
.br
\fC#include <ooc/object\&.h>\fP
.br
\fC#include 'object_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const void * \fBobj_add\fP (const void *_lhs, const void *_rhs)"
.br
.ti -1c
.RI "const void * \fBobj_sub\fP (const void *lhs, const void *rhs)"
.br
.ti -1c
.RI "const void * \fBobj_mul\fP (const void *lhs, const void *rhs)"
.br
.ti -1c
.RI "const void * \fBobj_div\fP (const void *lhs, const void *rhs)"
.br
.ti -1c
.RI "int \fBobj_to_int\fP (const void *_self)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const void* obj_add (const void * _lhs, const void * _rhs)"

.PP
Definition at line 5 of file math\&.c\&.
.PP
References OOCTraitMath::add, clsname(), get_class_header_msg(), and class_header::math\&.
.SS "const void* obj_div (const void * lhs, const void * rhs)"

.PP
Definition at line 29 of file math\&.c\&.
.SS "const void* obj_mul (const void * lhs, const void * rhs)"

.PP
Definition at line 24 of file math\&.c\&.
.SS "const void* obj_sub (const void * lhs, const void * rhs)"

.PP
Definition at line 18 of file math\&.c\&.
.SS "int obj_to_int (const void * _self)"

.PP
Definition at line 34 of file math\&.c\&.
.PP
References clsname(), and get_class_header_msg()\&.
.PP
Referenced by List_get_item()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
