/Users/igutek/Documents/Projects/ooc/src/math.c
NAME
/Users/igutek/Documents/Projects/ooc/src/math.c
SYNOPSIS
#include <ooc/math.h>
#include <ooc/object.h>
#include 'object_internal.h'
Functions
const void * obj_add (const void *_lhs, const void *_rhs)
const void * obj_sub (const void *lhs, const void *rhs)
const void * obj_mul (const void *lhs, const void *rhs)
const void * obj_div (const void *lhs, const void *rhs)
int obj_to_int (const void *_self)
Function Documentation
const void* obj_add (const void * _lhs, const void * _rhs)
Definition at line 5 of file math.c.
References OOCTraitMath::add, clsname(), get_class_header_msg(), and class_header::math.
const void* obj_div (const void * lhs, const void * rhs)
Definition at line 29 of file math.c.
const void* obj_mul (const void * lhs, const void * rhs)
Definition at line 24 of file math.c.
const void* obj_sub (const void * lhs, const void * rhs)
Definition at line 18 of file math.c.
int obj_to_int (const void * _self)
Definition at line 34 of file math.c.
References clsname(), and get_class_header_msg().
Referenced by List_get_item().
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.