.TH "/Users/igutek/Documents/Projects/ooc/src/object.c" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/src/object.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <ooc/object\&.h>\fP
.br
\fC#include <ooc/string\&.h>\fP
.br
\fC#include 'object_internal\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const void * \fB_new\fP (size_t argc,\&.\&.\&.)"
.br
.RI "Create a new ooc object\&. "
.ti -1c
.RI "void \fBdel\fP (const void *_object)"
.br
.RI "delete an ooc object "
.ti -1c
.RI "const char * \fBstr\fP (const void *_self)"
.br
.ti -1c
.RI "const void * \fBto_String\fP (const void *_object)"
.br
.ti -1c
.RI "void \fBprint\fP (const void *_self)"
.br
.ti -1c
.RI "size_t \fBsize\fP (const void *_self)"
.br
.RI "get size in bytes "
.ti -1c
.RI "const void * \fBtype\fP (const void *_self)"
.br
.RI "get ooc class object "
.ti -1c
.RI "size_t \fBlen\fP (const void *_self)"
.br
.ti -1c
.RI "const char * \fBclsname\fP (const void *_self)"
.br
.ti -1c
.RI "const void * \fBcopy\fP (const void *_self)"
.br
.ti -1c
.RI "bool \fBequals\fP (const void *_self, const void *_other)"
.br
.ti -1c
.RI "const void * \fBappend\fP (const void *_self, const void *_other)"
.br
.ti -1c
.RI "struct \fBclass_header\fP * \fBget_class_header_msg\fP (const void *_self, const char *message)"
.br
.ti -1c
.RI "const struct \fBclass_header\fP * \fBget_obj_type\fP (const void *_self, const void *class, const char *message)"
.br
.ti -1c
.RI "const struct \fBclass_header\fP * \fBget_class_header\fP (const void *_self)"
.br
.ti -1c
.RI "uint64_t \fBhash\fP (const void *_self)"
.br
.ti -1c
.RI "void * \fBset_item\fP (const void *_self, const void *_key, const void *_other)"
.br
.ti -1c
.RI "void \fBdel_item\fP (const void *_self, const void *_key)"
.br
.ti -1c
.RI "const void * \fBget_item\fP (const void *_self, const void *_key)"
.br
.ti -1c
.RI "const void * \fBiter\fP (const void *_self)"
.br
.ti -1c
.RI "const void * \fBnext\fP (const void *_self)"
.br
.ti -1c
.RI "void \fBkeys\fP (const void *object)"
.br
.ti -1c
.RI "void \fBvalues\fP (const void *_self)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const struct \fBclass_header\fP \fBClass\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const struct \fBclass_header\fP* get_class_header (const void * _self)\fC [inline]\fP"

.PP
Definition at line 219 of file object\&.c\&.
.PP
Referenced by del_item(), get_HashMap(), get_item(), hash(), insert_HashMap(), internal_insert_HashMap(), iter(), next(), and set_item()\&.
.SS "void keys (const void * object)"

.PP
Definition at line 292 of file object\&.c\&.
.SS "const char* str (const void * _object)"
End of Common functions 
.PP
Definition at line 56 of file object\&.c\&.
.PP
References get_class_header_msg(), and class_header::str\&.
.PP
Referenced by get_HashMap(), insert_HashMap(), List_to_str(), String_equal(), and to_String()\&.
.SS "const void* to_String (const void * _object)"

.PP
Definition at line 68 of file object\&.c\&.
.PP
References str(), and String\&.
.PP
Referenced by List_to_str()\&.
.SS "void values (const void * _self)"

.PP
Definition at line 296 of file object\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const struct \fBclass_header\fP Class"
\fBInitial value:\fP
.PP
.nf
= {
   \&.magic = MAGIC
}
.fi
.PP
Definition at line 6 of file object\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
