.TH "/Users/igutek/Documents/Projects/ooc/src/object_internal.h" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/src/object_internal.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'trait_math_internal\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP"
.br
.ti -1c
.RI "struct \fBObjectHeader\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAGIC\fP   ((unsigned long ) 0xBD71472)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAGIC   ((unsigned long ) 0xBD71472)"

.PP
Definition at line 7 of file object_internal\&.h\&.
.PP
Referenced by _new(), get_class_header_msg(), and get_obj_type()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
