.TH "/Users/igutek/Documents/Projects/ooc/include/ooc/object.h" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/include/ooc/object.h
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const void * \fBnew\fP (const void *class,\&.\&.\&.)"
.br
.RI "Create a new ooc object\&. "
.ti -1c
.RI "const void * \fBtype\fP (const void *self)"
.br
.RI "get ooc class object "
.ti -1c
.RI "void \fBdel\fP (const void *_object)"
.br
.ti -1c
.RI "size_t \fBsize\fP (const void *_object)"
.br
.ti -1c
.RI "const char * \fBclsname\fP (const void *_self)"
.br
.ti -1c
.RI "void \fBprint\fP (const void *_object)"
.br
.ti -1c
.RI "size_t \fBlen\fP (const void *_object)"
.br
.ti -1c
.RI "const void * \fBcopy\fP (const void *_object)"
.br
.ti -1c
.RI "bool \fBequals\fP (const void *_object, const void *_other)"
.br
.ti -1c
.RI "const char * \fBstr\fP (const void *_object)"
.br
.ti -1c
.RI "void * \fBto_String\fP (const void *_object)"
.br
.ti -1c
.RI "const void * \fBappend\fP (const void *_object, const void *_other)"
.br
.ti -1c
.RI "void * \fBinsert\fP (const void *_self, const void *_key, const void *item)"
.br
.ti -1c
.RI "const void * \fBget_item\fP (const void *_self, const void *_key)"
.br
.ti -1c
.RI "struct \fBclass_header\fP * \fBget_obj\fP (const void *_self, const char *message)"
.br
.ti -1c
.RI "const void * \fBiter\fP (const void *_object)"
.br
.ti -1c
.RI "uint64_t \fBhash\fP (const void *_self)"
.br
.ti -1c
.RI "const void * \fBnext\fP (const void *_self)"
.br
.ti -1c
.RI "void \fBdel_item\fP (const void *_self, const void *key)"
.br
.ti -1c
.RI "const struct \fBclass_header\fP * \fBget_class_header\fP (const void *_self)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const struct \fBclass_header\fP \fBClass\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const struct \fBclass_header\fP* get_class_header (const void * _self)\fC [inline]\fP"

.PP
Definition at line 180 of file object\&.c\&.
.PP
Referenced by del_item(), get_HashMap(), get_item(), hash(), insert(), insert_HashMap(), internal_insert_HashMap(), iter(), and next()\&.
.SS "const char* str (const void * _object)"
End of Common functions 
.PP
Definition at line 46 of file object\&.c\&.
.PP
References get_obj(), and class_header::str\&.
.PP
Referenced by get_HashMap(), insert_HashMap(), and String_equal()\&.
.SS "void* to_String (const void * _object)"

.SH "Variable Documentation"
.PP 
.SS "const struct \fBclass_header\fP Class"

.PP
Definition at line 5 of file object\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
