.TH "/Users/igutek/Documents/Projects/ooc/src/object_internal.h" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/src/object_internal.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAGIC\fP   ((unsigned long ) 0xBD71472)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAGIC   ((unsigned long ) 0xBD71472)"

.PP
Definition at line 6 of file object_internal\&.h\&.
.PP
Referenced by get_obj(), and new()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
