.TH "ObjectHeader" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const struct \fBclass_header\fP * \fBclass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 211 of file object_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const struct \fBclass_header\fP* ObjectHeader::class"

.PP
Definition at line 212 of file object_internal\&.h\&.
.PP
Referenced by _new()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
