/Users/igutek/Documents/Projects/ooc/src/object.c
NAME
/Users/igutek/Documents/Projects/ooc/src/object.c
SYNOPSIS
#include <assert.h>
#include <ooc/object.h>
#include <ooc/string.h>
#include 'object_internal.h'
Functions
const void * _new (size_t argc,...)
Create a new ooc object.
void del (const void *_object)
delete an ooc object
const char * str (const void *_self)
const void * to_String (const void *_object)
void print (const void *_self)
size_t size (const void *_self)
get size in bytes
const void * type (const void *_self)
get ooc class object
size_t len (const void *_self)
const char * clsname (const void *_self)
const void * copy (const void *_self)
bool equals (const void *_self, const void *_other)
const void * append (const void *_self, const void *_other)
struct class_header * get_class_header_msg (const void *_self, const char *message)
const struct class_header * get_obj_type (const void *_self, const void *class, const char *message)
const struct class_header * get_class_header (const void *_self)
uint64_t hash (const void *_self)
void * set_item (const void *_self, const void *_key, const void *_other)
void del_item (const void *_self, const void *_key)
const void * get_item (const void *_self, const void *_key)
const void * iter (const void *_self)
const void * next (const void *_self)
void keys (const void *object)
void values (const void *_self)
Variables
const struct class_header Class
Function Documentation
const struct class_header* get_class_header (const void * _self) [inline]
Definition at line 219 of file object.c.
Referenced by del_item(), get_HashMap(), get_item(), hash(), insert_HashMap(), internal_insert_HashMap(), iter(), next(), and set_item().
void keys (const void * object)
Definition at line 292 of file object.c.
const char* str (const void * _object)
End of Common functions
Definition at line 56 of file object.c.
References get_class_header_msg(), and class_header::str.
Referenced by get_HashMap(), insert_HashMap(), List_to_str(), String_equal(), and to_String().
const void* to_String (const void * _object)
Definition at line 68 of file object.c.
References str(), and String.
Referenced by List_to_str().
void values (const void * _self)
Definition at line 296 of file object.c.
Variable Documentation
const struct class_header Class
Initial value:
= {
   .magic = MAGIC
}
Definition at line 6 of file object.c.
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.