/Users/igutek/Documents/Projects/ooc/include/ooc/object.h
NAME
/Users/igutek/Documents/Projects/ooc/include/ooc/object.h
SYNOPSIS
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
Functions
const void * new (const void *class,...)
Create a new ooc object.
const void * type (const void *self)
get ooc class object
void del (const void *_object)
size_t size (const void *_object)
const char * clsname (const void *_self)
void print (const void *_object)
size_t len (const void *_object)
const void * copy (const void *_object)
bool equals (const void *_object, const void *_other)
const char * str (const void *_object)
void * to_String (const void *_object)
const void * append (const void *_object, const void *_other)
void * insert (const void *_self, const void *_key, const void *item)
const void * get_item (const void *_self, const void *_key)
struct class_header * get_obj (const void *_self, const char *message)
const void * iter (const void *_object)
uint64_t hash (const void *_self)
const void * next (const void *_self)
void del_item (const void *_self, const void *key)
const struct class_header * get_class_header (const void *_self)
Variables
const struct class_header Class
Function Documentation
const struct class_header* get_class_header (const void * _self) [inline]
Definition at line 180 of file object.c.
Referenced by del_item(), get_HashMap(), get_item(), hash(), insert(), insert_HashMap(), internal_insert_HashMap(), iter(), and next().
const char* str (const void * _object)
End of Common functions
Definition at line 46 of file object.c.
References get_obj(), and class_header::str.
Referenced by get_HashMap(), insert_HashMap(), and String_equal().
void* to_String (const void * _object)
Variable Documentation
const struct class_header Class
Definition at line 5 of file object.c.
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.