.TH "OOCTraitMath" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OOCTraitMath
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trait_math_internal\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBenabled\fP"
.br
.ti -1c
.RI "const void *(* \fBadd\fP )(const void *lhs, const void *rhs)"
.br
.ti -1c
.RI "const void *(* \fBsub\fP )(const void *lhs, const void *rhs)"
.br
.ti -1c
.RI "const void *(* \fBmul\fP )(const void *lhs, const void *rhs)"
.br
.ti -1c
.RI "const void *(* \fBdiv\fP )(const void *lhs, const void *rhs)"
.br
.ti -1c
.RI "int(* \fBto_int\fP )(const void *_self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file defines the functions and data members required by the math trait\&. 
.PP
Definition at line 9 of file trait_math_internal\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const void*(* OOCTraitMath::add) (const void *lhs, const void *rhs)"

.PP
Definition at line 11 of file trait_math_internal\&.h\&.
.PP
Referenced by obj_add()\&.
.SS "const void*(* OOCTraitMath::div) (const void *lhs, const void *rhs)"

.PP
Definition at line 14 of file trait_math_internal\&.h\&.
.SS "bool OOCTraitMath::enabled"

.PP
Definition at line 10 of file trait_math_internal\&.h\&.
.SS "const void*(* OOCTraitMath::mul) (const void *lhs, const void *rhs)"

.PP
Definition at line 13 of file trait_math_internal\&.h\&.
.SS "const void*(* OOCTraitMath::sub) (const void *lhs, const void *rhs)"

.PP
Definition at line 12 of file trait_math_internal\&.h\&.
.SS "int(* OOCTraitMath::to_int) (const void *_self)"

.PP
Definition at line 15 of file trait_math_internal\&.h\&.
.PP
Referenced by List_get_item()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
