.TH "Person" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Person
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <person\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP * \fBclass\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "char * \fBfirst\fP"
.br
.ti -1c
.RI "char * \fBlast\fP"
.br
.ti -1c
.RI "unsigned int \fBage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file person\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int Person::age"

.PP
Definition at line 11 of file person\&.h\&.
.SS "struct \fBclass_header\fP* Person::class"

.PP
Definition at line 7 of file person\&.h\&.
.SS "char* Person::first"

.PP
Definition at line 9 of file person\&.h\&.
.PP
Referenced by __construct__Person()\&.
.SS "char* Person::last"

.PP
Definition at line 10 of file person\&.h\&.
.PP
Referenced by __construct__Person()\&.
.SS "size_t Person::size"

.PP
Definition at line 8 of file person\&.h\&.
.PP
Referenced by __construct__Person(), and get_size_Person()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
