.TH "PersonClass" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PersonClass
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP \fBclass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file person\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP PersonClass::class"

.PP
Definition at line 13 of file person\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
