.TH "/Users/igutek/Documents/Projects/ooc/src/person.c" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/src/person.c
.SH SYNOPSIS
.br
.PP
\fC#include <ooc/person\&.h>\fP
.br
\fC#include 'object_internal\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPersonClass\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const void * \fB__construct__Person\fP (const void *self, va_list args)"
.br
.ti -1c
.RI "void * \fB__destruct__Person\fP (const void *self, va_list args)"
.br
.ti -1c
.RI "void \fBprint_Person\fP (const void *_self)"
.br
.ti -1c
.RI "size_t \fBget_size_Person\fP (const void *_self)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBPersonClass\fP \fBperson_class\fP"
.br
.ti -1c
.RI "void * \fBPerson\fP = &\fBperson_class\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const void * __construct__Person (const void * self, va_list args)"

.PP
Definition at line 29 of file person\&.c\&.
.PP
References Person::first, Person::last, Person, Person::size, and size()\&.
.SS "void* __destruct__Person (const void * self, va_list args)"

.SS "size_t get_size_Person (const void * _self)"

.PP
Definition at line 48 of file person\&.c\&.
.PP
References Person::size\&.
.SS "void print_Person (const void * _self)"

.PP
Definition at line 53 of file person\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "void* \fBPerson\fP = &\fBperson_class\fP"

.PP
Definition at line 24 of file person\&.c\&.
.PP
Referenced by __construct__Person()\&.
.SS "struct \fBPersonClass\fP person_class"
\fBInitial value:\fP
.PP
.nf
= {
    \&.class = {\&.magic = MAGIC, 
              \&.size  = (sizeof(struct Person)),
              \&.print = print_Person,
              \&.get_size = get_size_Person,
              \&.object_init = __construct__Person,
             }
}
.fi
.PP
Definition at line 15 of file person\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
