.TH "Point" 3 "Fri Sep 27 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <point\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP * \fBclass\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file point\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP* Point::class"

.PP
Definition at line 6 of file point\&.h\&.
.PP
Referenced by __construct__Point()\&.
.SS "size_t Point::size"

.PP
Definition at line 7 of file point\&.h\&.
.PP
Referenced by get_size_Point()\&.
.SS "double Point::x"

.PP
Definition at line 8 of file point\&.h\&.
.SS "double Point::y"

.PP
Definition at line 9 of file point\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
