.TH "String" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
String
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <string\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP * \fBclass\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "char * \fBstring_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file string\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP* String::class"

.PP
Definition at line 9 of file string\&.h\&.
.SS "size_t String::len"

.PP
Definition at line 11 of file string\&.h\&.
.PP
Referenced by String_get_len()\&.
.SS "size_t String::size"

.PP
Definition at line 10 of file string\&.h\&.
.PP
Referenced by String_get_size()\&.
.SS "char* String::string_data"

.PP
Definition at line 12 of file string\&.h\&.
.PP
Referenced by String_append(), and String_str()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
