.TH "StringClass" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringClass
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBclass_header\fP \fBclass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file string\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBclass_header\fP StringClass::class"

.PP
Definition at line 9 of file string\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
