/Users/igutek/Documents/Projects/ooc/src/string.c
NAME
/Users/igutek/Documents/Projects/ooc/src/string.c
SYNOPSIS
#include <ooc/string.h>
#include 'object_internal.h'
#include <stdlib.h>
Data Structures
struct StringClass
Macros
#define FNV_PRIME_32 16777619
#define FNV_OFFSET_32 2166136261U
Functions
size_t String_get_len (const void *_self)
size_t String_get_size (const void *_self)
const void * __construct__String (const void *_self, size_t argc, va_list args)
void print_String (void *_self)
const char * String_str (const void *_self)
const void * String_append (const void *_self, const void *_other)
bool String_equal (const void *_self, const void *_other)
const void * String_copy (const void *_self)
uint32_t FNV32 (char *s, size_t len)
uint64_t String_hash (const void *_self)
Variables
struct StringClass string_class
void * String = &string_class
Macro Definition Documentation
#define FNV_OFFSET_32 2166136261U
Definition at line 6 of file string.c.
Referenced by FNV32().
#define FNV_PRIME_32 16777619
Definition at line 5 of file string.c.
Referenced by FNV32().
Function Documentation
const void* __construct__String (const void * _self, size_t argc, va_list args)
Definition at line 24 of file string.c.
References len(), size(), and String.
uint32_t FNV32 (char * s, size_t len)
Definition at line 115 of file string.c.
References FNV_OFFSET_32, FNV_PRIME_32, hash(), and len().
Referenced by String_hash().
void print_String (void * _self)
Definition at line 44 of file string.c.
const void* String_append (const void * _self, const void * _other)
Definition at line 56 of file string.c.
References len(), size(), String, String::string_data, and type().
const void* String_copy (const void * _self)
Definition at line 110 of file string.c.
References String.
bool String_equal (const void * _self, const void * _other)
Definition at line 97 of file string.c.
References clsname(), str(), String, and type().
size_t String_get_len (const void * _self)
Definition at line 12 of file string.c.
References String::len.
size_t String_get_size (const void * _self)
Definition at line 18 of file string.c.
References String::size.
uint64_t String_hash (const void * _self)
Definition at line 126 of file string.c.
References FNV32().
const char* String_str (const void * _self)
Definition at line 50 of file string.c.
References String::string_data.
Variable Documentation
void* String = &string_class
Definition at line 163 of file string.c.
Referenced by __construct__String(), main(), String_append(), String_copy(), String_equal(), and to_String().
struct StringClass string_class
Initial value:
= {
    .class = {.magic = MAGIC,
              .size = sizeof(struct String),
              .object_init = __construct__String,
              .get_size = String_get_size,
              .get_len = String_get_len,
              .str = String_str,
              .copy = String_copy,
              .append = String_append,
              .hash = String_hash,
              .equals = String_equal,
              .object_name = "String"
             }
}
Definition at line 147 of file string.c.
Author
Generated automatically by Doxygen for Object-Oriented-C from the source code.