.TH "/Users/igutek/Documents/Projects/ooc/include/ooc/string.h" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/include/ooc/string.h
.SH SYNOPSIS
.br
.PP
\fC#include 'object\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBString\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void * \fBString\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void* \fBString\fP"

.PP
Definition at line 163 of file string\&.c\&.
.PP
Referenced by __construct__String(), main(), String_append(), String_copy(), String_equal(), and to_String()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
