.TH "/Users/igutek/Documents/Projects/ooc/src/trait_math_internal.h" 3 "Sat Sep 28 2019" "Object-Oriented-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/igutek/Documents/Projects/ooc/src/trait_math_internal.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBOOCTraitMath\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Object-Oriented-C from the source code\&.
